#!/bin/bash
# https://github.com/larrybotha/designer-dotfiles
# https://github.com/mathiasbynens/dotfiles/blob/master/.macos

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# macOS defaults (Finder, Dock, screenshots, power) live in osx/set-defaults.sh



#################################################################
### XCode Command Line Tools
#################################################################

echo 'install xcode command line tools'
echo '-----------------'
xcode-select --install
echo 'If a dialog appeared, finish installing Command Line Tools before continuing.'
read -p 'Press enter to continue...'



#################################################################
### GIT
#################################################################

# symlink git config + global gitignore (gitconfig sets excludesfile)
ln -s $HOME/.dotfiles/shell/.gitignore_global $HOME/.gitignore_global
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig


#################################################################
### ZSH
#################################################################

# install oh-my-zsh (RUNZSH/CHSH keep the installer from hijacking this script)
echo 'install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
RUNZSH=no CHSH=no sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions

# symlink zsh prefs
rm -f $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc



#################################################################
### Homebrew
#################################################################

echo 'install homebrew'
echo '----------------'
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# make brew usable in this shell (Apple Silicon)
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'install packages from Brewfile'
echo '----------------'
brew trust ngrok/ngrok 2>/dev/null || true
brew trust steipete/tap 2>/dev/null || true
brew bundle --file="$HOME/.dotfiles/Brewfile"



#################################################################
### iTerm2 profile (Maple Mono NF font)
#################################################################

echo 'install iTerm2 dynamic profile'
echo '----------------'
mkdir -p "$HOME/Library/Application Support/iTerm2/DynamicProfiles"
cp "$HOME/.dotfiles/iterm2/dotfiles-profile.json" "$HOME/Library/Application Support/iTerm2/DynamicProfiles/"
# make it the default profile (guid must match iterm2/dotfiles-profile.json)
defaults write com.googlecode.iterm2 "Default Bookmark Guid" -string "d07f11e5-0000-4000-8000-000000000001"



#################################################################
### Node
#################################################################

echo 'install NVM + Node 24.19.0 LTS'
echo '---------------'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm install 24.19.0
nvm alias default 24.19.0
git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm

# Grok Build (xAI) — no brew package; official npm distribution
npm install -g @xai-official/grok

# Ionic CLI for puffrate native/ iOS work
npm install -g @ionic/cli



#################################################################
### Done
#################################################################

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'all done'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. set some sensible os x defaults by running: $HOME/.dotfiles/osx/set-defaults.sh'
echo '2. make a .dotfiles-custom/shell/.(exports,aliases,functions,zshrc) for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo 'Please report issues!'
